version: '3'
services:

  flask:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: flask
    image: flask-python:3.8
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "True"
      APP_PORT: 5000
      MONGODB_DATABASE: flaskdb
      MONGODB_USERNAME: flaskuser
      MONGODB_PASSWORD: sua_senha_do_mongodb
      MONGODB_HOSTNAME: mongodb
    ports:
        - "80:5000"
    volumes:
      - appdata:/var/www
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: senha_do_root_do_mongodb
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db

volumes:
    mongodbdata:
        driver: local
    appdata:
        driver: local
        

